### ISSUE TITLE
Add type definition file to the output

### ISSUE THREAD

**Issue by ArtemZag** [maasencioh/jest-matcher-deep-close-to#14]
When I install this package via yarn or npm it doesn't contain any type definition file.
Would be nice to add it.

Something like this (based on your index.d.ts file):
```
declare module "jest-matcher-deep-close-to" {
    export function toBeDeepCloseTo(
        received: number | number[] | object,
        expected: number | number[] | object,
        decimals?: number
    ): {
        message(): string;
        pass: boolean;
    };
    export function toMatchCloseTo(
        received: number | number[] | object,
        expected: number | number[] | object,
        decimals?: number
    ): {
        message(): string;
        pass: boolean;
    };

    declare global {
        namespace jest {
            interface Matchers<R> {
                toBeDeepCloseTo: (expected: number | number[] | object, decimals?: number) => R;
                toMatchCloseTo: (expected: number | number[] | object, decimals?: number) => R;
            }
        }
    }
}
```

**Comment by rob893** [comment]
I had this same issue. I just put the index.d.ts file from here into the node module, but it is annoying to do that for each computer that I work on.

**Comment by lummish** [comment]
Looks like the maintainers have fixed the issue in the source code, but those changes have yet to be published on NPM. Until they bump the NPM version, here's a workaround:

If you don't already have one, create a `@types` directory somewhere in your repository path (mine is at `src/@types`). Inside of this directory, create another directory called `jest-matcher-deep-close-to`. This directory will have a single file, `index.d.ts`, with the following contents (note: I have made some small modifications to the current `index.d.ts`):

``` typescript
// src/@types/jest-matcher-deep-close-to/index.d.ts

declare namespace jest {
  interface Matchers<R> {
    toBeDeepCloseTo: (expected: number | number[] | object, decimals?: number) => R;
    toMatchCloseTo: (expected: number | number[] | object, decimals?: number) => R;
  }
}

declare module 'jest-matcher-deep-close-to' {
  export function toBeDeepCloseTo(
    received: number | number[] | object,
    expected: number | number[] | object,
    decimals?: number,
  ): {
    message(): string;
    pass: boolean;
  };

  export function toMatchCloseTo(
    received: number | number[] | object,
    expected: number | number[] | object,
    decimals?: number,
  ): {
    message(): string;
    pass: boolean;
  };
}
``` 

Newer versions of TypeScript should pick up this module declaration automatically. If they don't you may need to modify your compiler options `types` and/or `typeRoots`.

@rob893 This should make it much easier to work on multiple machines/reinstall packages as you'll have your own declaration committed to source control.

**Comment by maasencioh** [comment]
The new version was done in typescript, so everything should be already natively available

**Comment by wholebuzz** [comment]
```error TS2339: Property 'toMatchCloseTo' does not exist on type 'JestMatchers<[string, number][]>'.```

Using version `2.0.1`.
