### ISSUE TITLE
Ambient jest.d.ts not visible from ./lib/index.d.ts

### ISSUE THREAD

**Issue by deluksic** [maasencioh/jest-matcher-deep-close-to#19]
Ambient types from jest.d.ts are not visible by default when installing. For now the workaround is to copy this file locally to the source folder, but it would be nice if it was injected into output.

**Comment by maasencioh** [comment]
Hi, by [default the compiler doesn't copy `.d.ts` files](https://stackoverflow.com/questions/56018167/typescript-does-not-copy-d-ts-files-to-build), but now everything should be in the next release. Thank you for reporting it
