### ISSUE TITLE
Unexpected difference from toBeCloseTo

### ISSUE THREAD

**Issue by dmwyatt** [maasencioh/jest-matcher-deep-close-to#23]
This passes:

```js
expect(0.25005635416666666).toBeCloseTo(0.25);
```

This fails:

```js
expect([0.25005635416666666]).toBeDeepCloseTo([0.25]);
```

I would expect the two cases to work the same.

**Comment by maasencioh** [comment]
Hi, there was a difference between the default precision value of the matchers, thank you for reporting it
